"""
One-time setup script — creates all Azure resources for ResumeRanker.

Usage (PowerShell):
    Copy-Item .env.example .env   # fill in real values first
    python setup_azure.py

Run again at any time to re-create / update resources.
"""

import os
import sys
import requests
from dotenv import load_dotenv
from azure.storage.blob import BlobServiceClient
from azure.core.exceptions import ResourceExistsError

load_dotenv()

# ── Config ────────────────────────────────────────────────────────
STORAGE_CONN  = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
RESUME_CONT   = os.getenv("RESUME_CONTAINER_NAME", "resumes")
JD_CONT       = os.getenv("JD_CONTAINER_NAME", "jds")

SEARCH_EP     = os.getenv("AZURE_SEARCH_ENDPOINT", "").rstrip("/")
SEARCH_KEY    = os.getenv("AZURE_SEARCH_API_KEY", "")

OPENAI_EP     = os.getenv("OPENAI_ENDPOINT", "").rstrip("/")
OPENAI_KEY    = os.getenv("OPENAI_API_KEY", "")
EMBED_DEPLOY  = os.getenv("EMBEDINGS_OPENAI_DEPLOYMENT_NAME", "text-embedding-ada-002")
# text-embedding-ada-002 produces 1536-dim vectors; update if you switch models
VECTOR_DIMS   = 1536

INDEX_NAME    = os.getenv("SEARCH_INDEX_NAME",      "resume-ranker-index")
INDEXER_NAME  = os.getenv("SEARCH_INDEXER_NAME",    "resume-ranker-indexer")
DS_NAME       = os.getenv("SEARCH_DATASOURCE_NAME", "resume-ranker-datasource")
SS_NAME       = os.getenv("SEARCH_SKILLSET_NAME",   "resume-ranker-skillset")

API_VER = "2024-07-01"
HEADERS = {"Content-Type": "application/json", "api-key": SEARCH_KEY}


# ── Helpers ───────────────────────────────────────────────────────
def _put(resource_path: str, body: dict) -> bool:
    url = f"{SEARCH_EP}/{resource_path}?api-version={API_VER}"
    r = requests.put(url, headers=HEADERS, json=body, timeout=30)
    if r.status_code not in (200, 201):
        print(f"    ERROR {r.status_code}: {r.text[:400]}")
        return False
    return True


def _run_step(label: str, fn) -> bool:
    print(f"\n[{label}]")
    ok = fn()
    print(f"    {'OK' if ok else 'FAILED'}")
    return ok


# ── Step 1 — Blob containers ──────────────────────────────────────
def create_containers() -> bool:
    client = BlobServiceClient.from_connection_string(STORAGE_CONN)
    for name in (RESUME_CONT, JD_CONT):
        try:
            client.create_container(name)
            print(f"    created: {name}")
        except ResourceExistsError:
            print(f"    already exists: {name}")
    return True


# ── Step 2 — Data source ──────────────────────────────────────────
def create_datasource() -> bool:
    return _put(f"datasources/{DS_NAME}", {
        "name": DS_NAME,
        "type": "azureblob",
        "credentials": {"connectionString": STORAGE_CONN},
        "container": {"name": RESUME_CONT},
    })


# ── Step 3 — Index with vector field ─────────────────────────────
def create_index() -> bool:
    return _put(f"indexes/{INDEX_NAME}", {
        "name": INDEX_NAME,
        "fields": [
            # chunk_id is the unique key per chunk (auto-generated by index projections)
            {"name": "chunk_id",   "type": "Edm.String",              "key": True,  "filterable": True,  "retrievable": True},
            # parent_id links each chunk back to its source blob
            {"name": "parent_id",  "type": "Edm.String",              "key": False, "filterable": True,  "retrievable": True},
            {"name": "title",      "type": "Edm.String",              "searchable": True, "filterable": True, "retrievable": True, "sortable": True},
            {"name": "chunk",      "type": "Edm.String",              "searchable": True, "retrievable": True, "analyzer": "en.microsoft"},
            {
                "name": "text_vector",
                "type": "Collection(Edm.Single)",
                "searchable": True,
                "retrievable": False,   # no need to return vectors to the app
                "dimensions": VECTOR_DIMS,
                "vectorSearchProfile": "hnsw-profile",
            },
        ],
        "vectorSearch": {
            "algorithms": [
                {
                    "name": "hnsw-config",
                    "kind": "hnsw",
                    "hnswParameters": {
                        "m": 4, "efConstruction": 400, "efSearch": 500, "metric": "cosine",
                    },
                }
            ],
            "profiles": [{"name": "hnsw-profile", "algorithm": "hnsw-config"}],
        },
    })


# ── Step 4 — Skillset (split → embed → project) ───────────────────
def create_skillset() -> bool:
    return _put(f"skillsets/{SS_NAME}", {
        "name": SS_NAME,
        "description": "Split documents into chunks and embed each chunk",
        "skills": [
            {
                "@odata.type": "#Microsoft.Skills.Text.SplitSkill",
                "name": "split-skill",
                "context": "/document",
                "defaultLanguageCode": "en",
                "textSplitMode": "pages",
                "maximumPageLength": 2000,
                "pageOverlapLength": 200,
                "inputs":  [{"name": "text",      "source": "/document/content"}],
                "outputs": [{"name": "textItems", "targetName": "pages"}],
            },
            {
                "@odata.type": "#Microsoft.Skills.Text.AzureOpenAIEmbeddingSkill",
                "name": "embedding-skill",
                "context": "/document/pages/*",
                "resourceUri": OPENAI_EP,
                "apiKey": OPENAI_KEY,
                "deploymentId": EMBED_DEPLOY,
                "modelName": EMBED_DEPLOY,
                "inputs":  [{"name": "text",      "source": "/document/pages/*"}],
                "outputs": [{"name": "embedding", "targetName": "text_vector"}],
            },
        ],
        # Index projections write one search document per chunk
        "indexProjections": {
            "selectors": [
                {
                    "targetIndexName": INDEX_NAME,
                    "parentKeyFieldName": "parent_id",
                    "sourceContext": "/document/pages/*",
                    "mappings": [
                        {"name": "chunk",       "source": "/document/pages/*"},
                        {"name": "text_vector", "source": "/document/pages/*/text_vector"},
                        {"name": "title",       "source": "/document/metadata_storage_name"},
                    ],
                }
            ],
            "parameters": {"projectionMode": "generatedKeyAsId"},
        },
    })


# ── Step 5 — Indexer ──────────────────────────────────────────────
def create_indexer() -> bool:
    return _put(f"indexers/{INDEXER_NAME}", {
        "name": INDEXER_NAME,
        "dataSourceName": DS_NAME,
        "targetIndexName": INDEX_NAME,
        "skillsetName": SS_NAME,
        "parameters": {
            "batchSize": 1,
            "maxFailedItems": -1,
            "maxFailedItemsPerBatch": -1,
            "configuration": {
                "dataToExtract": "contentAndMetadata",
                "parsingMode": "default",   # Azure cracks PDF/DOCX/TXT automatically
            },
        },
        "fieldMappings": [],
        "outputFieldMappings": [],
    })


# ── Main ──────────────────────────────────────────────────────────
if __name__ == "__main__":
    required = {
        "AZURE_STORAGE_CONNECTION_STRING": STORAGE_CONN,
        "AZURE_SEARCH_ENDPOINT":           SEARCH_EP,
        "AZURE_SEARCH_API_KEY":            SEARCH_KEY,
        "OPENAI_ENDPOINT":                 OPENAI_EP,
        "OPENAI_API_KEY":                  OPENAI_KEY,
    }
    missing = [k for k, v in required.items() if not v]
    if missing:
        print("ERROR — missing required env vars:")
        for m in missing:
            print(f"  {m}")
        print("\nCopy .env.example to .env and fill in real values, then re-run.")
        sys.exit(1)

    results = [
        _run_step("1. Blob containers",    create_containers),
        _run_step("2. Search data source", create_datasource),
        _run_step("3. Search index",       create_index),
        _run_step("4. Search skillset",    create_skillset),
        _run_step("5. Search indexer",     create_indexer),
    ]

    if all(results):
        print("\nSetup complete.")
        print("Next: upload resumes to the 'resumes' container (via the app or upload_blobs.py),")
        print("      then the indexer will run automatically on the next schedule or you can")
        print("      trigger it manually from the app's upload panel.")
    else:
        print("\nSetup finished with errors — fix the issues above and re-run.")
        sys.exit(1)
